[package]
name = "tss-ecdsa"
version = "0.0.0"
description = "Multi-party ECDSA signing"
authors = ["Kevin Lewi <klewi@fb.com>", "Don Beaver <dbeaver@fb.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"

[features]
default = []
flame_it = ["flame", "flamer"]

[dependencies]
anyhow = "1"
k256 = { version = "0.9.6", features = ["arithmetic", "digest", "sha256", "ecdsa-core"] }
libpaillier = "0.2.1"
bincode = "1.3"
displaydoc = { version = "0.2", default-features = false }
ecdsa = { version = "0.12", features = ["hazmat"] }
hex = "0.4.2"
rand = "0.8"
sha2 = "0.9"
generic-array = "0.14.4"
regex = "1.5"
merlin = "3"
integer-encoding = "3.0.2"
lazy_static = "1.4"
elliptic-curve = "0.10.6"
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.3", optional = true }

[dev-dependencies]
