[package]
name = "tss-ecdsa"
version = "0.0.0"
description = "Multi-party ECDSA signing"
authors = ["Kevin Lewi <klewi@fb.com>", "Don Beaver <dbeaver@fb.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
k256 = { version = "0.9.6", features = ["arithmetic"] }
libpaillier = "0.2.1"
bincode = "1.3"
hex = "0.4.2"
rand = "0.8"
