[package]
name = "tss-ecdsa"
version = "0.0.0"
description = "Multi-party ECDSA signing"
authors = ["Kevin Lewi <klewi@fb.com>", "Don Beaver <dbeaver@fb.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
k256 = { version = "0.9.6", features = ["arithmetic", "digest", "sha256", "ecdsa-core"] }
libpaillier = "0.2.1"
bincode = "1.3"
ecdsa = { version = "0.12", features = ["hazmat"] }
hex = "0.4.2"
rand = "0.8"
sha2 = "0.9"
generic-array = "0.14.4"
