[package]
name = "tss-ecdsa"
version = "0.0.0"
description = "Multi-party ECDSA signing"
authors = ["Kevin Lewi <klewi@fb.com>", "Don Beaver <dbeaver@fb.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"

[features]
default = []
flame_it = ["flame", "flamer"]

[dependencies]
anyhow = "1"
k256 = { version = "0.10", features = ["arithmetic", "digest", "sha256", "ecdsa", "serde"] }
libpaillier = "0.2"
bincode = "1"
displaydoc = { version = "0.2", default-features = false }
hex = "0.4"
rand = "0.8"
sha2 = "0.9"
serde = "1"
generic-array = "0.14"
regex = "1"
merlin = "3"
integer-encoding = "3"
lazy_static = "1"
flame = { version = "0.2", optional = true }
flamer = { version = "0.3", optional = true }

[dev-dependencies]
